### ISSUE TITLE
Importing algorithms error

### ISSUE THREAD

**Issue by cjohnson-bf** [moloch--/hashlookup#2]
Looks like you might have previously tried to fix this, but it's still not working for me. Maybe I'm doing something wrong? Let me know if I can provide any more info.

```
$ python --version
Python 2.7.12
$ python3 --version
Python 3.5.2
$ python hashlookup.py
Traceback (most recent call last):
  File "hashlookup.py", line 40, in <module>
    from .algorithms import algorithms
ValueError: Attempted relative import in non-package
$ python3 hashlookup.py
Traceback (most recent call last):
  File "hashlookup.py", line 40, in <module>
    from .algorithms import algorithms
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by moloch--** [comment]
Should be fixed per this commit https://github.com/moloch--/hashlookup/commit/c4abe292c4fc1c0fb442feb9c14d0c7268c54228

Note only Python 3.6 and later is supported.

**Comment by cjohnson-bf** [comment]
3.6 fixes the issue. Thanks!
